
@host = http://localhost:8000
### Create People
POST {{host}}/peoples
Content-Type: application/json

{
    "name":"Linus",
    "email":"linus@tes.com",
    "phone":"+ 123000 666",
    "ssj":"sw"
}

### List peoples
GET {{host}}/peoples


### Update people
PUT {{host}}/peoples/1
Content-Type: application/json

{
    "name":"Charlie Brown",
    "email":"charlie@test.co",
    "phone":"+ 123000 789"
}

### Delete 
DELETE {{host}}/peoples/8